version: '3.8'

services:
  fastify:
    build: ./server
    container_name: fastify_app
    ports:
      - '3000:3000'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - fastify
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
